USE [master]
GO

/****** Object:  Database [PRJ301_FALL2022_Assignment]    Script Date: 11/8/2022 11:53:41 PM ******/
CREATE DATABASE [PRJ301_FALL2022_Assignment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRJ301_FALL2022_Assignment', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.GIAOLANG\MSSQL\DATA\PRJ301_FALL2022_Assignment.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRJ301_FALL2022_Assignment_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.GIAOLANG\MSSQL\DATA\PRJ301_FALL2022_Assignment_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRJ301_FALL2022_Assignment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET ARITHABORT OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET  MULTI_USER 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PRJ301_FALL2022_Assignment] SET  READ_WRITE 
GO


